{"filename": "python-zope-exceptions-5.2-1-any.pkg.tar.zst", "name": "python-zope-exceptions", "base": "python-zope-exceptions", "version": "5.2-1", "desc": "Generic exceptions and implementations for Zope", "csize": "39171", "isize": "229686", "md5sum": "2091a4e468ee6278174dc7292fa951ec", "sha256sum": "9ecfbcbcdc7de54486fdbdd6886ebf130f4fa70edc0eaa2ddc98dfd8cc1d4c2a", "pgpsig": "iHUEABYKAB0WIQTrPXZP9dh+CBij4OXwXowSExrrXgUCZyH3egAKCRDwXowSExrrXsY8AQC1KKDBZsEsvxf3QVhSoSTifxLTWIPgBS1kBwLXE7/JHAEAn/JrNHk6MqaYgVjBSsoL08BgbwJZX9VaWWlVOyFtgAU=", "url": "https://github.com/zopefoundation/zope.exceptions", "license": "ZPL-2.1", "arch": "any", "builddate": "1730279252", "packager": "Carl Smedstad <carsme@archlinux.org>", "depends": ["python", "python-zope-interface"], "makedepends": ["git", "python-build", "python-installer", "python-setuptools", "python-wheel"], "checkdepends": ["python-zope-testrunner"]}