{"filename": "python-exceptiongroup-1.1.3-1-any.pkg.tar.xz", "name": "python-exceptiongroup", "base": "python-exceptiongroup", "version": "1.1.3-1", "desc": "Backport of PEP 654 (exception groups)", "csize": "31416", "isize": "139366", "md5sum": "d0777c3e6413207e64e4b9e337547562", "sha256sum": "6cb4e08caed4a2722c6e836802f65792ac723d5538ea3116e845eaf22a30ae45", "pgpsig": "iQIzBAABCAAdFiEEaLNTfzmjE7PldNBndxk/FSvb5qYFAmTk7HkACgkQdxk/FSvb5qYTSw//f8iOsrhAXCekZp8ISnsBY6c8TT3zJ0cNiur6llNmwvPWaGDaWs+FlCsD48hUifreL0vIvr9dTq+3zPwJHx0v3YtebF3Yq4MA2syAZlEdIB00OWT6JvJcJk13ob128bN9beAlaGGlZjCPmxSE+ZA7Hq79CGOM/kVrxlhf4MRJ1ENybF2XKfyDQp/J9s7BiPlzMsTFBhZg8OfFvqGXGFmN3y+u8/Qimf8PcBt8y7XMvH/VoXeazoLABnOyyT7FBE6D9/mqorxcGFqYn2mbx+VZs4Feyy8Ds7BOi3zTLqxqZI3z/LyX4SG0E5fnRrrFYutqONVXegHH+dCfDyPjdMnVUc9BqqJQQwGqe5NjjLgyA+sGEotnmdNH8C2uZwBX5r45m/URsn9fOqrLmuAWr574Vf/XENTZixgzcD90nC1fgSQa92rk3it44aFR96BqaOykuheIJFeriQfrZ9JOKZdeMElCOdzB7n9Az/Wz5T5ZZqPf+PJvG2xs1M8d3nyJSxTNSjAGbhdSWBbOVsaWlssPJaYXWupIh1PAAdvz9HEWRTxzSodvrO4cVtRkLkYjWHfJraRp0wmlWYLMeWciwADIRu+aoGeTyT1HfKqByNn7NmJ8HewrafzHNEGTrNDGKWZsF+oiTxyp+p0Nc/4r0+PvusOqlIDPPuht7y1h78Meiy8=", "url": "https://github.com/agronholm/exceptiongroup", "license": "MIT", "arch": "any", "builddate": "1692724332", "packager": "Arch Linux ARM Build System <builder+n1@archlinuxarm.org>", "depends": ["python<=3.11.3"], "makedepends": ["python-build", "python-installer", "python-wheel", "python-flit-scm"], "checkdepends": ["python-pytest"], "tokens": ["python-exceptiongroup", "python-exceptiongroup_aarch64", "python-exceptiongroup_unstable", "python-exceptiongroup_aarch64_unstable"]}