{"filename": "python-exceptiongroup-1.1.2-1-any.pkg.tar.xz", "name": "python-exceptiongroup", "base": "python-exceptiongroup", "version": "1.1.2-1", "desc": "Backport of PEP 654 (exception groups)", "csize": "30676", "isize": "132959", "md5sum": "04e64e781c7bbd6decf0a0201c8019f0", "sha256sum": "38cfd501daf8bcdffa89e5ab7f9b31376e9cdd8f1d41f9aca6f3bebed49eda2f", "pgpsig": "iQIzBAABCAAdFiEEaLNTfzmjE7PldNBndxk/FSvb5qYFAmSj53oACgkQdxk/FSvb5qZwARAAoackouvjgUoWh11urWUzBCZ7GxwJaEbIIptMP2mHDSK3ukeNY5Wt9Mrjh7beGfvpHcJ2AOlpmfw8u8LWwFMVrTaXPNz5krTkgkWRFmKatm1apBzysz7EvmeA2D/7BblpbNlLSLrckdns8cTOynGAbFuGyUisNuqwSazAjwo7yNKeVjCdP1Nn9I0O35Jy6q4B6X1uJc8CyjMMKd2ivkTEb63KJ4uL1DN14iDrB1CS8wNtQs7imxz/Na7L9XTyLvluxeoengLuA3iy8SPVbC7jMa2+v6VkSX5GPfDP//g7ZG70bp2IEVUuRVJJkuq9LL85Yk5GCnQ6qcUUnH3JlEuzwudg7AlzVlZeciy/nO1UQ+SBg2vyottohUU4f/K+/lQhKZc6EnqUvuKVr3sVuDkMy8KoLcadfAnKN7wz5wBbujiF4n3eUO4oEv89G9q2ILDyqRBqaH4zcuLhlVLB51YQNCH7+ITG1TSUjjlDx+QJ9MaE/gFiHbPF951VX8GeXXwGC1pvYyAP2WWtDWFic3dRioG0GUuuOQdyNFRkYFfuwaY3R7+k7tw3jtveyIWVB3BhZgzDU4BzY6I/XOjXdQYnSxINUtApH9Eracqq6/VdApzrbTMxPz6J5nx4SBSGQJEaNzIXwvMyX96/rr2jtkAMoZpwOztJlpblfVaLMKSGfjo=", "url": "https://github.com/agronholm/exceptiongroup", "license": "MIT", "arch": "any", "builddate": "1688463216", "packager": "Arch Linux ARM Build System <builder+seattle@archlinuxarm.org>", "depends": ["python<=3.11.3"], "makedepends": ["python-build", "python-installer", "python-wheel", "python-flit-scm"], "checkdepends": ["python-pytest"], "tokens": ["python-exceptiongroup", "python-exceptiongroup_aarch64", "python-exceptiongroup_unstable", "python-exceptiongroup_aarch64_unstable"]}