{"filename": "python-pytest-rerunfailures-12.0-1-any.pkg.tar.xz", "name": "python-pytest-rerunfailures", "base": "python-pytest-rerunfailures", "version": "12.0-1", "desc": "A plugin for py.test that re-runs failed tests to eliminate intermittent failures", "csize": "25924", "isize": "121719", "md5sum": "f97fdef1b4b9c82d960ed2799674458d", "sha256sum": "fcfdeb92bfe75f80dc6a646d00ae81b5de743ba23b835b422e533390513ec5b0", "pgpsig": "iQIzBAABCAAdFiEEaLNTfzmjE7PldNBndxk/FSvb5qYFAmSpexwACgkQdxk/FSvb5qYdmg//bNGQhJp75GnOllk9wQUc5Y9oFYAKStLPgEBRLLlVwpih15tyL6ZFyalcxkMrT49FIbXFb7UYCjGJW/I8rwRsyz+GmnhCicFdP4S2Lkl319OllK3UIhQKoVDoBcKDQFbskncFgCVWA2Ztm/otP9qtqjm3RtldnksGh9diCfEWGa5CJl+/8C0lvx+2wJ+UDk32DUgbKMaNrFOlZUbuxdQ8DvLfAZqyirPKo630VZbGGuEXMFyL/XKV2meE91UvlvcMYrFYvxJqZFxiDVJM23QJZEUDqoMUA0FH7olSwHsXRNGjTe9tCQuf2kXsFi6PAwVZroW+MLW41U8+G7v35Iv7ZcWMa0+uhXTABQDp6ckRdI04/nYvnEN1dzZs1J9Cy2gIVT/UnLncUO2s0dwxcRSBYt7fp3fgbp1kOGY8qJPOCcHnfscdYpCt7lPGD2JAoVGHuj3DfCmZA+52mSC3tnvutXDO51jDUB79kJkhnoG6tiBObskc4IQwymlz+Vom4+sC5Kaynnl+dfNXVtPOHOIrwyxUwD6c5/DJQuARemuw5qtnneONSVzji6L8yt9JqdG1OlR8/hmY/qOiUZE7LSYdsDZ2mDnU7NV02Up3uqSnpm3NhPzawV1Q71oHRRaVlpQeScPrOr9B4CGCJnf8/FGBK1P+7rWr3v1iB0hsBL+WE08=", "url": "https://github.com/pytest-dev/pytest-rerunfailures/", "license": "MPL2", "arch": "any", "builddate": "1688828687", "packager": "Arch Linux ARM Build System <builder+n1@archlinuxarm.org>", "depends": ["python", "python-packaging", "python-pytest"], "optdepends": "python-pytest-xdist: for recovering from crashes", "makedepends": ["python-build", "python-installer", "python-setuptools", "python-wheel"], "checkdepends": ["python-pytest-xdist"], "tokens": ["python-pytest-rerunfailures", "python-pytest-rerunfailures_aarch64", "python-pytest-rerunfailures_unstable", "python-pytest-rerunfailures_aarch64_unstable"]}