{"filename": "python-zope-exceptions-5.0.1-3-any.pkg.tar.zst", "name": "python-zope-exceptions", "base": "python-zope-exceptions", "version": "5.0.1-3", "desc": "Generic exceptions and implementations for Zope", "csize": "36594", "isize": "221342", "md5sum": "0e6dbc51ec8688054c3378128fc94693", "sha256sum": "d8cc1e8a7812898aae4507090cf9af212fbf108b41792194efc90938ae161673", "pgpsig": "iQEzBAABCAAdFiEEFRnVq6Zb9vwrc8dWek52CV2KUuQFAmYRJYEACgkQek52CV2KUuS/KQf+KjMvST23N3nnu3B/cr/4BjtLQBnN0kSVxspmJK8ZPLKyf4eE4FhlotLG9m1dyV/YkWfZB5zl3/ei+wjAQ1psTdzuo7qADcIIPa9Ul/3/5i3izgTubyYmb70XmmICZsEAXCgJuGiil0Z0jVc31TdbAKIQCvg3MIwKZRT9qV0qNrp007YXix6iDxKEPGcUeGVTAdOtB1XMj4OJLGPV82KiVjLGT1JoGZtiRuUrZ2ZBlQG1LSGgJxMUxMCzfHwOy0lvDozrGPtl/UpP/jS0mZIufOdXMn+QAQci8fuGXHVBiOjgz+Kpt5AtdsqWAeJOW4zrIbqyGCN4Dsmz00TUiq8StA==", "url": "https://github.com/zopefoundation/zope.exceptions", "license": "ZPL", "arch": "any", "builddate": "1712399726", "packager": "Antonio Rojas <arojas@archlinux.org>", "depends": ["python-setuptools", "python-zope-interface"], "makedepends": ["python-setuptools", "python-zope-interface"], "checkdepends": ["python-zope-testrunner"]}