{"filename": "python-exceptiongroup-1.2.0-1-any.pkg.tar.xz", "name": "python-exceptiongroup", "base": "python-exceptiongroup", "version": "1.2.0-1", "desc": "Backport of PEP 654 (exception groups)", "csize": "33604", "isize": "148788", "md5sum": "880273d1beb941f964173da38b2ecb86", "sha256sum": "3d230c4ec60f75430824260ad307d950ea9b098670e7527d62174fd642bbdd7e", "pgpsig": "iQIzBAABCAAdFiEEaLNTfzmjE7PldNBndxk/FSvb5qYFAmWO4BEACgkQdxk/FSvb5qbfiQ/9EpFgg6x/zqBdKHdpZ5HmBxQhQ3wLnGIHD4wChFUZMmQq5yq8r84ImkJsCQF/renLbOobj4Q7AOQl9sB6YawFISWrWSSlBHW34LM46sTwHzgOyzt0EEDMWP+6UhlkyChPGzzktQqDESH2ZQPhXuUD8RBjvcnvoli5T5gUWN7d/gJv5nLMoUVCnPMb4KP7AYHWmD+03iCPSXkxCcFGd0sEnX8amQ4eOf92ezbOPNoAPSfk4tocWjgfetl/nhMtMqUkMQ163h4Z64IaiXHkmqwR/QTnzJ+nSFQsBuKpwDNoMdWPXw41/LpZuA+sr/vV/lzy6X/eRkXwaBEpY32RDroe+ZlKxWW51nYrsHMTyspsNgsG240i/cCAqoC2BEecSTYu/wSBcMlIwdoTyftqU/34DBZK1J9ChnpZEr9AhgEfRrrgT4RW7HL7t+8egdP3/frQbt8mJpFi9Ts6MDgIzZgZRHC+hkMWQeuXhDtn3S/jhYS2nrPnkqXviLd4lAtcMgbYsUmLOlA9EH/LvuqdUxwpDlrconQ/mysl2KjjLVHX++X/cv1+RljErQjozUCa9SRIAkVw0epEZQgRtBDHmyb+3Q2Oa+4g4+iLFG9LCyZIaQj/Uw65imy6dUFNy0D6YBZoKbzkQrE/nu+1oz4hEWelr+lotg+3tqecETqxAUgG6ZY=", "url": "https://github.com/agronholm/exceptiongroup", "license": "MIT", "arch": "any", "builddate": "1703862276", "packager": "Arch Linux ARM Build System <builder+n1@archlinuxarm.org>", "depends": ["python"], "makedepends": ["python-build", "python-installer", "python-wheel", "python-flit-scm"], "checkdepends": ["python-pytest"]}